### ISSUE TITLE
Have you considered building an assertion library?

### ISSUE THREAD

**Issue by slang25** [amantinband/throw#61]
Hey, I'm really impressed with the design this library, it's very well thought out.

Have you considered if some of this could be repurposed or made available in a way that would be usable as an assertion library?

I mean it could today, but it would be more idiomatic to throw a specific type of assertion exception, perhaps with a `.Assert()...` extension that does the `Validatable<TValue>` capture.

**Comment by truegoodwill** [comment]
You can get halfway there by creating your own extension method: 

```csharp
public static Validatable<TValue> Assert<TValue>(this TValue value)
{
  return value.Throw<SpecificException>();
}
```

The problem is that it doesn't allow you to add an actual message or parameter name to the exception that is created. The closest you can get to that (with the current version of the library) is to add a constructor method that accepts the parameter name as an argument, but any of the lovely custom messages provided by the library are lost: 

```csharp
public static Validatable<TValue> Assert<TValue(this TValue value)
{
  return value.Throw(paramName => new SpecificException($"There was a problem with {paramName}.");
}
```
I have raised an issue separately that, amongst other things, suggests adding the following overload feature to the library, that would probably satisfy your need: 

```csharp
public static Validatable<TValue> Assert<TValue(this TValue value)
{
//   need a new function made available to produce this result
  return value.Throw((paramName, message) => new SpecificException($"{message} (Parameter '{paramName}').");
}
```

**Comment by amantinband** [comment]
Thanks, @slang25, I think it's well thought out as well 😅 Are you familiar with [`FluentAssertions`](https://github.com/fluentassertions/fluentassertions)?
